### ISSUE TITLE
django-custom_field-2.9-py2.7.egg/custom_field/migrations is "Not a directory."

### ISSUE THREAD

**Issue by sglatlas** [willseward/django-custom-field#7]
File "/usr/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 93, in load_disk
    for name in os.listdir(directory):
OSError: [Errno 20] Not a directory: '/usr/local/lib/python2.7/dist-packages/django_custom_field-2.9-py2.7.egg/custom_field/migrations'

**Comment by willseward** [comment]
Django version? Does it work from master?

**Comment by sglatlas** [comment]
I think is one is my bad, sorry.  I reinstalled and did a python manage.py makemigrations, and the issue seems to be resolved.  Or maybe it was the lobotomy.

**Comment by willseward** [comment]
Lol! Glad I could help!
